version: 3

dotenv: [".env"]

includes:
  base:
    taskfile: ./scripts/tasks/base
  build:
    taskfile: ./scripts/tasks/build
  run:
    taskfile: ./scripts/tasks/run
  e2e:
    taskfile: ./scripts/tasks/e2e
