version: 3

tasks:
  clear:
    internal: true
    silent: true
    run: once
    cmds:
      - clear || true

  default:
    desc: "The default task"
    deps: ["clear"]
    cmds:
      - task: run:cli-run
